############# navigation ##############

# main menu
[[main]]
name = "é¦–é "
pageRef = "/"
weight = 1

[[main]]
name = "é—œæ–¼"
pageRef = "/about"
weight = 2

[[main]]
name = "Podcast"
pageRef = "/podcast"
weight = 3

[[main]]
name = "æ›¸å–®"
weight = 4

[[main]]
weight = 1
parent = "æ›¸å–®"
name = "ğŸ‘å¿…è®€ï¼Œæ›¸å–®ğŸ“š"
pageRef = "pages/reading_list"

[[main]]
weight = 2
parent = "æ›¸å–®"
name = "å•†æ¥­/è²¡ç¶“"
pageRef = "/tags/å•†æ¥­/è²¡ç¶“/"

[[main]]
weight = 2
parent = "æ›¸å–®"
name = "ç†è²¡/è§€å¿µ"
pageRef = "/tags/ç†è²¡/è§€å¿µ/"


[[main]]
weight = 3
parent = "æ›¸å–®"
name = "å•†å‹™/è¶¨å‹¢"
pageRef = "/tags/å•†å‹™/è¶¨å‹¢/"

[[main]]
weight = 4
parent = "æ›¸å–®"
name = "å¿ƒç†/å‹µå¿—"
pageRef = "/tags/å¿ƒç†/å‹µå¿—/"

[[main]]
weight = 5
parent = "æ›¸å–®"
name = "è¡ŒéŠ·/å¸‚å ´"
pageRef = "/tags/è¡ŒéŠ·/å¸‚å ´/"

[[main]]
weight = 5
parent = "æ›¸å–®"
name = "äººæ–‡/å²å“²"
pageRef = "/tags/äººæ–‡/å²å“²/"

[[main]]
weight = 6
parent = "æ›¸å–®"
name = "è¦ªå­/æ•™é¤Š"
pageRef = "/tags/è¦ªå­/æ•™é¤Š/"

[[main]]
name = "æ–‡ç« "
pageRef = "/blog"
weight = 5

[[main]]
weight = 1
parent = "æ–‡ç« "
name = "æ‰€æœ‰æ–‡ç« "
pageRef = "/blog"

[[main]]
weight = 2
parent = "æ–‡ç« "
name = "è²¡å‹™è¦åŠƒèˆ‡å¿ƒæ…‹"
pageRef = "/categories/è²¡å‹™è¦åŠƒèˆ‡å¿ƒæ…‹/"

[[main]]
weight = 3
parent = "æ–‡ç« "
name = "é–±è®€å¿ƒå¾—"
pageRef = "/categories/é–±è®€å¿ƒå¾—/"

[[main]]
weight = 4
parent = "æ–‡ç« "
name = "è²¡å‹™å·¥å…·èˆ‡é‡‘èå•†å“"
pageRef = "/categories/è²¡å‹™å·¥å…·èˆ‡é‡‘èå•†å“/"

[[main]]
weight = 5
parent = "æ–‡ç« "
name = "è·æ¶¯èˆ‡ç”Ÿæ´»"
pageRef = "/categories/è·æ¶¯èˆ‡ç”Ÿæ´»/"

[[main]]
weight = 6
parent = "æ–‡ç« "
name = "Podcastç¯€ç›®"
pageRef = "/categories/Podcastç¯€ç›®/"

[[main]]
weight = 6
name = "è¿½è¹¤"

[[main]]
weight = 1
parent = "è¿½è¹¤"
name = "threads"
url = "https://www.threads.net/@lazytoberich/"

[[main]]
weight = 2
parent = "è¿½è¹¤"
name = "instagram"
url = "https://www.instagram.com/lazytoberich/"

[[main]]
weight = 3
parent = "è¿½è¹¤"
name = "facebook"
url = "https://www.facebook.com/lazytoberich"

[[main]]
weight = 4
parent = "è¿½è¹¤"
name = "discord"
url = "https://discord.gg/xeYCvQWBPx"

# footer menu
[[footer]]
name = "é—œæ–¼"
pageRef = "/about"
weight = 1

[[footer]]
name = "Podcast"
pageRef = "/podcast"
weight = 2

[[footer]]
name = "éš±ç§æ¬Šæ”¿ç­–"
pageRef = "pages/privacy-policy"
weight = 3
