# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/lazy.png"

[footer]
since = 2018
customText = """æ¸¬è©¦ä¸€ä¸‹"""

[dateFormat]
published = "Jan 02, 2023"
lastUpdated = "Jan 02, 2023 20:30 MST"

[sidebar]
emoji = "ğŸ’°"
subtitle = """é€ƒé›¢æ­£ç¶“å…«ç™¾çš„é‡‘èåœˆ<br>
è§£é–‹ç†è²¡å¾ˆå°ˆæ¥­çš„èª¤æœƒ<br>
åªæƒ³ç”¨æ—¥å¸¸ç”Ÿæ´»çš„èªè¨€<br>
å¶çˆ¾ç©¿æ’é»ç‚ä¸ŠåŠ ç«çƒ¤<br>
ç”¨ç°¡å–®æ˜“æ‡‚çš„ç†è²¡æ–¹æ³•<br>
è®“æ‡¶æƒ°è·Ÿæ•ˆç‡å¯ä»¥å¯¦ç¾<br>"""

[sidebar.avatar]
enabled = true
local = true
src = "img/Lazytoberich.png"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY LazyToBeRich æ‡¶å¾—è®Šæœ‰éŒ¢"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "disqus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
